export enum PayPalEventType {
    CHECKOUT_ORDER_APPROVED="CHECKOUT.ORDER.APPROVED",
    PAYMENT_CAPTURE_COMPLETED="PAYMENT.CAPTURE.COMPLETED",
    PAYMENT_CAPTURE_DENIED="PAYMENT.CAPTURE.DENIED",
    PAYMENT_CAPTURE_DECLINED="PAYMENT.CAPTURE.DECLINED",
}