export enum AuditEventType {
  // DEFAULT
  DEFAULT = "DEFAULT",

  // USER
  USER_LOGGED_IN = "USER_LOGGED_IN",
  USER_LOGGED_OUT = "USER_LOGGED_OUT",
  USER_PROFILE_UPDATED = "USER_PROFILE_UPDATED",
  USER_ACCOUNT_DEACTIVATED = "USER_ACCOUNT_DEACTIVATED",

  // BOOKING
  BOOKING_CREATED = "BOOKING_CREATED",
  BOOKING_UPDATED = "BOOKING_UPDATED",
  BOOKING_CANCELLED = "BOOKING_CANCELLED",

  // PAYMENT - internal transaction states
  PAYMENT_TRANSACTION_INITIATED = "PAYMENT_TRANSACTION_INITIATED",
  PAYMENT_TRANSACTION_CREATED = "PAYMENT_TRANSACTION_CREATED",
  PAYMENT_TRANSACTION_UPDATED = "PAYMENT_TRANSACTION_UPDATED",
  PAYMENT_TRANSACTION_FAILED = "PAYMENT_TRANSACTION_FAILED",
  PAYMENT_TRANSACTION_COMPLETED = "PAYMENT_TRANSACTION_COMPLETED",
  PAYMENT_TRANSACTION_CANCELLED = "PAYMENT_TRANSACTION_CANCELLED",

  // PAYMENT - internal transaction details states
  PAYMENT_TRANSACTION_DETAILS_ADDED = "PAYMENT_TRANSACTION_DETAILS_ADDED",

  // PAYMENT - provider events
  PROVIDER_CHECKOUT_ORDER_APPROVED = "PROVIDER_CHECKOUT_ORDER_APPROVED",
  PROVIDER_PAYMENT_ORDER_CREATED = "PROVIDER_PAYMENT_ORDER_CREATED",
  PROVIDER_PAYMENT_ORDER_CANCELLED = "PROVIDER_PAYMENT_ORDER_CANCELLED",
  PROVIDER_PAYMENT_CAPTURE_PENDING="PROVIDER_PAYMENT_CAPTURE_PENDING",
  PROVIDER_PAYMENT_CAPTURE_COMPLETED = "PROVIDER_PAYMENT_CAPTURE_COMPLETED",
  PROVIDER_PAYMENT_CAPTURE_DECLINED = "PROVIDER_PAYMENT_CAPTURE_DECLINED",
  PROVIDER_PAYMENT_CAPTURE_DENIED = "PROVIDER_PAYMENT_CAPTURE_DENIED",
  PROVIDER_PAYMENT_CAPTURE_REFUNDED = "PROVIDER_PAYMENT_CAPTURE_REFUNDED",
  PROVIDER_PAYMENT_ABANDONED = "PROVIDER_PAYMENT_ABANDONED",
  PROVIDER_UNKNOWN = "PROVIDER_UNKNOWN"

}
